# SPDX-FileCopyrightText: 2025-present Raki Rahman <mdrakiburrahman@gmail.com>
#
# SPDX-License-Identifier: MIT

from typing import Mapping

PACKAGE_VERSION_ENV_VAR = "PACKAGE_VERSION"

FAB_TOKEN_ENV_VAR = "FAB_TOKEN"
FAB_TOKEN_AZURE_ENV_VAR = "FAB_TOKEN_AZURE"
FAB_TOKEN_GRAPH_ENV_VAR = "FAB_TOKEN_GRAPH"
FAB_TOKEN_CICD_ENV_VAR = "FAB_TOKEN_CICD"
FAB_TOKEN_SQL_ENV_VAR = "FAB_TOKEN_SQL"
FAB_PATH_ENV_VAR = "FAB_PATH"

RAYFIN_TOKEN_ENV_VAR = "RAYFIN_TOKEN"
RAYFIN_WORKSPACE_ID_ENV_VAR = "RAYFIN_WORKSPACE_ID"
RAYFIN_TENANT_ID_ENV_VAR = "RAYFIN_TENANT_ID"
RAYFIN_APP_ROOT_ENV_VAR = "RAYFIN_APP_ROOT"
RAYFIN_UID_ENV_VAR = "RAYFIN_UID"
RAYFIN_GID_ENV_VAR = "RAYFIN_GID"

FWD_RAYFIN_WORKSPACE_ID_ENV_VAR = "FWD_RAYFIN_WORKSPACE_ID"
FWD_RAYFIN_APP_BACKEND_ID_ENV_VAR = "FWD_RAYFIN_APP_BACKEND_ID"
FWD_RAYFIN_SQL_DATABASE_ID_ENV_VAR = "FWD_RAYFIN_SQL_DATABASE_ID"
FWD_RAYFIN_SQL_SERVER_ENV_VAR = "FWD_RAYFIN_SQL_SERVER"
FWD_RAYFIN_SQL_DATABASE_NAME_ENV_VAR = "FWD_RAYFIN_SQL_DATABASE_NAME"
FWD_RAYFIN_SQL_ACCESS_TOKEN_ENV_VAR = "FWD_RAYFIN_SQL_ACCESS_TOKEN"
RAYFIN_MIGRATION_ENVIRONMENT_VARIABLES = (FWD_RAYFIN_WORKSPACE_ID_ENV_VAR, FWD_RAYFIN_APP_BACKEND_ID_ENV_VAR, FWD_RAYFIN_SQL_DATABASE_ID_ENV_VAR, FWD_RAYFIN_SQL_SERVER_ENV_VAR, FWD_RAYFIN_SQL_DATABASE_NAME_ENV_VAR, FWD_RAYFIN_SQL_ACCESS_TOKEN_ENV_VAR)
SENSITIVE_ENVIRONMENT_VARIABLE_MARKERS = ("TOKEN", "PASSWORD", "SECRET", "PRIVATE_KEY", "CONNECTION_STRING", "SQL_SERVER", "SQL_DATABASE_NAME")


def redact_sensitive_values(value: str | bytes, environment: Mapping[str, str]) -> str:
    """Mask known sensitive environment values, longest first to avoid partial leaks."""
    text = value.decode(errors="replace") if isinstance(value, bytes) else value
    secrets = {secret for key, secret in environment.items() if secret and any(marker in key.upper() for marker in SENSITIVE_ENVIRONMENT_VARIABLE_MARKERS)}
    for secret in sorted(secrets, key=len, reverse=True):
        text = text.replace(secret, "******")
    return text


GIT_ROOT_ENV_VAR = "GIT_ROOT"
UNIQUE_ENV_ID_ENV_VAR = "UNIQUE_ENV_ID"
USER_APP_ID_ENV_VAR = "USER_APP_ID"
USER_DISPLAY_NAME_ENV_VAR = "USER_DISPLAY_NAME"
USER_OBJECT_ID_ENV_VAR = "USER_OBJECT_ID"
USER_PRINCIPAL_TYPE_ENV_VAR = "USER_PRINCIPAL_TYPE"

MANAGER_SKIP_ENABLED_VALUE = "1"

SKIP_ENTITLEMENT_CHECK_ENV_VAR = "FAB_SKIP_ENTITLEMENT_CHECK"
SKIP_ALERT_DEPLOYMENT_ENV_VAR = "FAB_SKIP_ALERT_DEPLOYMENT"
SKIP_FABRIC_CAPACITY_DEPLOYMENT_ENV_VAR = "FAB_SKIP_FABRIC_CAPACITY_DEPLOYMENT"
SKIP_FABRIC_WORKSPACE_DEPLOYMENT_ENV_VAR = "FAB_SKIP_FABRIC_WORKSPACE_DEPLOYMENT"
SKIP_GIT_LINK_DEPLOYMENT_ENV_VAR = "FAB_SKIP_GIT_LINK_DEPLOYMENT"
SKIP_GATEWAY_DEPLOYMENT_ENV_VAR = "FAB_SKIP_GATEWAY_DEPLOYMENT"
SKIP_TEMPLATE_DEPLOYMENT_ENV_VAR = "FAB_SKIP_TEMPLATE_DEPLOYMENT"
SKIP_RBAC_DEPLOYMENT_ENV_VAR = "FAB_SKIP_RBAC_DEPLOYMENT"
SKIP_SEED_DEPLOYMENT_ENV_VAR = "FAB_SKIP_SEED_DEPLOYMENT"
SKIP_SHORTCUT_DEPLOYMENT_ENV_VAR = "FAB_SKIP_SHORTCUT_DEPLOYMENT"
SKIP_SPARK_DEPLOYMENT_ENV_VAR = "FAB_SKIP_SPARK_DEPLOYMENT"
SKIP_MODEL_DEPLOYMENT_ENV_VAR = "FAB_SKIP_MODEL_DEPLOYMENT"
SKIP_MONITORING_DEPLOYMENT_ENV_VAR = "FAB_SKIP_MONITORING_DEPLOYMENT"

SCOPE_TOKEN_ENV_VARS = {
    "https://analysis.windows.net/powerbi/api": FAB_TOKEN_ENV_VAR,
    "https://management.azure.com": FAB_TOKEN_AZURE_ENV_VAR,
    "https://database.windows.net": FAB_TOKEN_SQL_ENV_VAR,
    "https://graph.microsoft.com": FAB_TOKEN_GRAPH_ENV_VAR,
    "https://graph.microsoft.us": FAB_TOKEN_GRAPH_ENV_VAR,
    "https://dod-graph.microsoft.us": FAB_TOKEN_GRAPH_ENV_VAR,
    "https://microsoftgraph.chinacloudapi.cn": FAB_TOKEN_GRAPH_ENV_VAR,
}
