# SPDX-FileCopyrightText: 2025-present Raki Rahman <mdrakiburrahman@gmail.com>
#
# SPDX-License-Identifier: MIT

PACKAGE_VERSION_ENV_VAR = "PACKAGE_VERSION"

FAB_TOKEN_ENV_VAR = "FAB_TOKEN"
FAB_TOKEN_AZURE_ENV_VAR = "FAB_TOKEN_AZURE"
FAB_TOKEN_GRAPH_ENV_VAR = "FAB_TOKEN_GRAPH"
FAB_TOKEN_CICD_ENV_VAR = "FAB_TOKEN_CICD"
FAB_PATH_ENV_VAR = "FAB_PATH"

GIT_ROOT_ENV_VAR = "GIT_ROOT"
UNIQUE_ENV_ID_ENV_VAR = "UNIQUE_ENV_ID"
USER_APP_ID_ENV_VAR = "USER_APP_ID"
USER_DISPLAY_NAME_ENV_VAR = "USER_DISPLAY_NAME"
USER_OBJECT_ID_ENV_VAR = "USER_OBJECT_ID"
USER_PRINCIPAL_TYPE_ENV_VAR = "USER_PRINCIPAL_TYPE"

MANAGER_SKIP_ENABLED_VALUE = "1"

SKIP_ENTITLEMENT_CHECK_ENV_VAR = "FAB_SKIP_ENTITLEMENT_CHECK"
SKIP_ALERT_DEPLOYMENT_ENV_VAR = "FAB_SKIP_ALERT_DEPLOYMENT"
SKIP_FABRIC_CAPACITY_DEPLOYMENT_ENV_VAR = "FAB_SKIP_FABRIC_CAPACITY_DEPLOYMENT"
SKIP_FABRIC_WORKSPACE_DEPLOYMENT_ENV_VAR = "FAB_SKIP_FABRIC_WORKSPACE_DEPLOYMENT"
SKIP_GIT_LINK_DEPLOYMENT_ENV_VAR = "FAB_SKIP_GIT_LINK_DEPLOYMENT"
SKIP_TEMPLATE_DEPLOYMENT_ENV_VAR = "FAB_SKIP_TEMPLATE_DEPLOYMENT"
SKIP_RBAC_DEPLOYMENT_ENV_VAR = "FAB_SKIP_RBAC_DEPLOYMENT"
SKIP_SEED_DEPLOYMENT_ENV_VAR = "FAB_SKIP_SEED_DEPLOYMENT"
SKIP_SHORTCUT_DEPLOYMENT_ENV_VAR = "FAB_SKIP_SHORTCUT_DEPLOYMENT"
SKIP_SPARK_DEPLOYMENT_ENV_VAR = "FAB_SKIP_SPARK_DEPLOYMENT"
SKIP_MODEL_DEPLOYMENT_ENV_VAR = "FAB_SKIP_MODEL_DEPLOYMENT"
SKIP_MONITORING_DEPLOYMENT_ENV_VAR = "FAB_SKIP_MONITORING_DEPLOYMENT"

SCOPE_TOKEN_ENV_VARS = {
    "https://analysis.windows.net/powerbi/api": FAB_TOKEN_ENV_VAR,
    "https://management.azure.com": FAB_TOKEN_AZURE_ENV_VAR,
    "https://graph.microsoft.com": FAB_TOKEN_GRAPH_ENV_VAR,
    "https://graph.microsoft.us": FAB_TOKEN_GRAPH_ENV_VAR,
    "https://dod-graph.microsoft.us": FAB_TOKEN_GRAPH_ENV_VAR,
    "https://microsoftgraph.chinacloudapi.cn": FAB_TOKEN_GRAPH_ENV_VAR,
}
